1. Removed 3rd-party lib (lwl). From now on it should be downloaded and compiled separately. 2. Added Makefile for lwl compiling using OpenWrt SDK. 3. Updated README files which now include instructions for lwl compiling. 4. Log system is updated: now every message also contain filename and line number.

diff --git a/diem/CoT/configure b/diem/CoT/configure
--- a/diem/CoT/configure
+++ b/diem/CoT/configure
@@ -15517,8 +15517,95 @@ if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Unable to link to fcgi library. Please install Fast CGI library first." >&5
-echo "$as_me: error: Unable to link to fcgi library. Please install Fast CGI library first." >&2;}
+  { { echo "$as_me:$LINENO: error: Unable to link to libfcgi. Please install Fast CGI library first." >&5
+echo "$as_me: error: Unable to link to libfcgi. Please install Fast CGI library first." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+{ echo "$as_me:$LINENO: checking for library containing lwl_alloc" >&5
+echo $ECHO_N "checking for library containing lwl_alloc... $ECHO_C" >&6; }
+if test "${ac_cv_search_lwl_alloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char lwl_alloc ();
+int
+main ()
+{
+return lwl_alloc ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' lwl; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_lwl_alloc=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_lwl_alloc+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_lwl_alloc+set}" = set; then
+  :
+else
+  ac_cv_search_lwl_alloc=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_lwl_alloc" >&5
+echo "${ECHO_T}$ac_cv_search_lwl_alloc" >&6; }
+ac_res=$ac_cv_search_lwl_alloc
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Unable to link to liblwl. Please install LWL library first." >&5
+echo "$as_me: error: Unable to link to liblwl. Please install LWL library first." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -17630,7 +17717,7 @@ fi
 done
 
 
-ac_config_files="$ac_config_files Makefile 3rd-party/lwl/Makefile src/common/Makefile src/client/Makefile src/adapters/Makefile src/server/Makefile src/test/Makefile"
+ac_config_files="$ac_config_files Makefile src/common/Makefile src/client/Makefile src/adapters/Makefile src/server/Makefile src/test/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -18576,7 +18663,6 @@ do
     "depfiles") CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
     "libtool") CONFIG_COMMANDS="$CONFIG_COMMANDS libtool" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-    "3rd-party/lwl/Makefile") CONFIG_FILES="$CONFIG_FILES 3rd-party/lwl/Makefile" ;;
     "src/common/Makefile") CONFIG_FILES="$CONFIG_FILES src/common/Makefile" ;;
     "src/client/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/Makefile" ;;
     "src/adapters/Makefile") CONFIG_FILES="$CONFIG_FILES src/adapters/Makefile" ;;
